name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          # Taken from https://github.com/kirschbaum-development/laravel-test-runner-container/blob/master/8.2/Dockerfile
          extensions: mbstring, mysql, xml, xsl, zip, curl, bcmath, intl, bz2

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Test PHP code
        run: composer test-with-coverage

      - name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@v2
